org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=26.1.2
fabric_loader_version=0.19.1
fabric_api_version=0.152.1+26.1.2
quickshulker_version=3.0.1
itemscroller_compile_version=0.31.4
itemscroller_min_version=0.31.0

mod_id=shulkerbox_sort
mod_name=Shulker Box Sort
mod_version=2.1.4
mod_group=com.cntrident.shulkerboxsort
